### ISSUE TITLE
116th Congress CDIR Unfound

### ISSUE THREAD

**Issue by chrisbabayans** [usgpo/collections#10]
Hi,

The 116th Congress seems to be missing from the CDIR collection

https://api.govinfo.gov/collections/CDIR/2018-01-01T00:00:00Z/?pageSize=100&offset=0&api_key=DEMO_KEY. Edited comment to use DEMO_KEY.

**Comment by llaplant** [comment]
Thank you for your comment.  When it is available, it will also be in the CDIR RSS feed https://www.govinfo.gov/rss/cdir.xml.

**Comment by chrisbabayans** [comment]
> Thank you for your comment. When it is available, it will also be in the CDIR RSS feed https://www.govinfo.gov/rss/cdir.xml.

When do you think it will be ready? I urgently need the information for my application. Would it help t call the GPO and ask them to publish it here? Is there an alternative source for legislator names, zip codes, counties & parties?

Update: Found the number for the congressional publishing services division of the GPO. I'm on it :) 

Update 2: No timeline on the release. "Usually ready by the first half of the session"
