### ISSUE TITLE
Inconsistent Casing in CDIR

### ISSUE THREAD

**Issue by chrisbabayans** [usgpo/collections#11]
In the 21st district of the directory linked below, "Zip Codes:" breaks precedent of ZIP being in all caps. 

https://api.govinfo.gov/packages/CDIR-2018-10-29/granules/CDIR-2018-10-29-NY/htm?api_key=DEMO_KEY

**Comment by llaplant** [comment]
Thank you for bringing this to our attention. Note, it is consistent with the PDF. https://api.govinfo.gov/packages/CDIR-2018-10-29/granules/CDIR-2018-10-29-NY/pdf?api_key=DEMO_KEY. Edited comment to use DEMO_KEY.
