### ISSUE TITLE
Regular Expressions

### ISSUE THREAD

**Issue by cschwem2er** [usgpo/collections#2]
Hello,

many thanks for uploading the regex documentation here. I'm currently trying to automatically detect all witnesses for congressional hearings. As far as I can understand you provide two patterns, `witnessP` and `witnessP2`, for this. However, each of these patterns again includes two separate regular expressions. Could you please explain how to chain all these expressions in order to come up with a list of witnesses?

I have no problem with using one of them in Python, e.g.

```
witnessTitleP1_1 =re.compile("\\n(\\w.+?)(?:oral (?:statement|testimony))?\\.*\\s+\\d+(?=\\s*\\n)", 
                             flags=re.IGNORECASE | re.DOTALL)

```

but am not sure how to properly combine everything.

**Comment by jonquandt** [comment]
@methodds -- I spoke with one of our search engineers. It looks like `witnessP` is actually deprecated. `witnessP2` is what you should use. 

I'm going to update the document to remove the `witnessP` regex to minimize future confusion.

**Comment by cschwem2er** [comment]
Thank you very much for the update. There is still one thing I do not understand however: Why is `witnessP2` written as two consecutive expressions?

witnessP2 =

 `{"\\n *(\\w.+?)(?:oral (?:statement|testimony))?\\.*\\s+\\d+(?=\\s*\\n)",`
_part1_
`"((?<=\\n)\\s*\\n[a-zA-Z][^\\n]+?\\:\\s*\\n)|((?<=\\n)\\s*\\n {10,40}[a-zA-Z]+[^\\n]*)"}` 
_part2_

   CASE_INSENSITIVE + DOTALL

Is the idea to first check for _part1_ and then for _part2_ within all _part1_ results? I'm not used to this notation.

**Comment by jonquandt** [comment]
Sorry for the delay in getting back to you.

Look at the two expressions this way:

{matchRegex, endRegex}

Matching (matchRegex) will occur from the beginning of the sting to the first character of the matching endRegex (exclusive).

Let me know if you need more info.
