### ISSUE TITLE
Root govinfo.gov redirect is dropping the path

### ISSUE THREAD

**Issue by konklone** [usgpo/collections#5]
I typed `govinfo.gov/app/collection/comps` into my browser (Chrome), and it redirected me to `https://www.govinfo.gov` (the home page). Same when I explicitly went to `https://govinfo.gov/app/collection/comps`. 

I expected it to redirect me to `https://www.govinfo.gov/app/collection/comps`.

**Comment by jonquandt** [comment]
@konklone - looking into it. You can definitely get there via the UI - try browsing via [category browse](https://www.govinfo.gov/app/browse/category) in the mean time.

**Comment by jonquandt** [comment]
this is fixed - the bare https://govinfo.gov/app/collection/comps (and similar requests) should now get to the intended page. Thanks for finding that!

**Comment by konklone** [comment]
:+1: Thanks!
